### ISSUE TITLE
Reference Error i not defined

### ISSUE THREAD

**Issue by Ilovegym66** [dbweb-ch/ioBroker.rtspstream#2]
Hi, thank you very much for this great adapter!
Sometimes following error comes up:

`2020-01-01 07:20:17.332  - error: rtspStream.0 (4570) uncaught exception: i is not defined
2020-01-01 07:20:17.333  - error: rtspStream.0 (4570) ReferenceError: i is not defined
    at WebSocketServer.wsServer.broadcast (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:103:54)
    at VideoStream.on (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:109:26)
    at VideoStream.emit (events.js:198:13)
    at Mpeg1Muxer.mpeg1Muxer.on (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:47:17)
    at Mpeg1Muxer.emit (events.js:198:13)
    at Socket.Mpeg1Muxer.stream.stdout.on (/opt/iobroker/node_modules/node-rtsp-stream/mpeg1muxer.js:39:17)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
2020-01-01 07:20:17.794  - info: host.iobroker instance system.adapter.freifunk.0 terminated with code 0 (NO_ERROR)
2020-01-01 07:20:17.841  - info: rtspStream.0 (4570) terminating
2020-01-01 07:20:17.842  - info: rtspStream.0 (4570) Terminated (NO_ERROR): Without reason
2020-01-01 07:20:18.367  - error: host.iobroker Caught by controller[1]: frame=23656 fps= 20 q=2.0 size=   58981kB time=00:19:46.35 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.367  - error: host.iobroker Caught by controller[2]: frame=23665 fps= 20 q=2.0 size=   58994kB time=00:19:46.86 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.367  - error: host.iobroker Caught by controller[3]: frame=23681 fps= 20 q=2.0 size=   59044kB time=00:19:47.65 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.367  - error: host.iobroker Caught by controller[4]: frame=23682 fps= 20 q=2.0 size=   59045kB time=00:19:47.72 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.368  - error: host.iobroker Caught by controller[5]: frame=23696 fps= 20 q=2.0 size=   59076kB time=00:19:48.37 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.368  - error: host.iobroker Caught by controller[6]: frame=23709 fps= 20 q=2.0 size=   59108kB time=00:19:49.02 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.368  - error: host.iobroker Caught by controller[7]: frame=23724 fps= 20 q=2.0 size=   59141kB time=00:19:49.81 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.368  - error: host.iobroker Caught by controller[8]: frame=23731 fps= 20 q=2.0 size=   59164kB time=00:19:50.10 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.368  - error: host.iobroker Caught by controller[9]: frame=23741 fps= 20 q=2.0 size=   59191kB time=00:19:50.60 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.368  - error: host.iobroker Caught by controller[10]: frame=23755 fps= 20 q=2.0 size=   59223kB time=00:19:51.32 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.368  - error: host.iobroker Caught by controller[11]: frame=23762 fps= 20 q=1.6 size=   59243kB time=00:19:51.68 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.369  - error: host.iobroker Caught by controller[12]: frame=23774 fps= 20 q=1.6 size=   59271kB time=00:19:52.26 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.369  - error: host.iobroker Caught by controller[13]: frame=23784 fps= 20 q=2.0 size=   59292kB time=00:19:52.76 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.369  - error: host.iobroker Caught by controller[14]: frame=23790 fps= 20 q=2.0 size=   59312kB time=00:19:53.05 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.369  - error: host.iobroker Caught by controller[15]: frame=23804 fps= 20 q=2.0 size=   59344kB time=00:19:53.77 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.369  - error: host.iobroker Caught by controller[16]: frame=23818 fps= 20 q=2.0 size=   59377kB time=00:19:54.42 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.369  - error: host.iobroker Caught by controller[17]: frame=23824 fps= 20 q=2.0 size=   59397kB time=00:19:54.78 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.369  - error: host.iobroker Caught by controller[18]: frame=23829 fps= 20 q=2.0 size=   59402kB time=00:19:54.99 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.369  - error: host.iobroker Caught by controller[19]: frame=23839 fps= 20 q=2.0 size=   59433kB time=00:19:55.50 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.370  - error: host.iobroker Caught by controller[20]: frame=23885 fps= 20 q=2.0 size=   59556kB time=00:19:57.80 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.370  - error: host.iobroker Caught by controller[21]: frame=23895 fps= 20 q=2.0 size=   59580kB time=00:19:58.30 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.370  - error: host.iobroker Caught by controller[22]: frame=23905 fps= 20 q=2.0 size=   59597kB time=00:19:58.81 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.370  - error: host.iobroker Caught by controller[23]: frame=23915 fps= 20 q=2.0 size=   59621kB time=00:19:59.38 bitrate= 407.2kbits/s dup=0 drop=4    
2020-01-01 07:20:18.370  - error: host.iobroker Caught by controller[24]: frame=23926 fps= 20 q=2.0 size=   59652kB time=00:19:59.82 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.370  - error: host.iobroker Caught by controller[25]: frame=23936 fps= 20 q=2.0 size=   59682kB time=00:20:00.39 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.370  - error: host.iobroker Caught by controller[26]: frame=23946 fps= 20 q=2.0 size=   59706kB time=00:20:00.90 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.371  - error: host.iobroker Caught by controller[27]: frame=23957 fps= 20 q=2.0 size=   59734kB time=00:20:01.40 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.371  - error: host.iobroker Caught by controller[28]: frame=23967 fps= 20 q=2.0 size=   59759kB time=00:20:01.98 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.371  - error: host.iobroker Caught by controller[29]: frame=23975 fps= 20 q=2.0 size=   59772kB time=00:20:02.26 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.371  - error: host.iobroker Caught by controller[30]: frame=23991 fps= 20 q=2.0 size=   59819kB time=00:20:03.13 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.371  - error: host.iobroker Caught by controller[31]: frame=24001 fps= 20 q=2.0 size=   59840kB time=00:20:03.63 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.371  - error: host.iobroker Caught by controller[32]: frame=24011 fps= 20 q=2.0 size=   59865kB time=00:20:04.14 bitrate= 407.3kbits/s dup=0 drop=4    
frame=24032 fps= 20 q=2.0 size=   59925kB time=00:20:05.22 bitrate= 407.3kbits/s dup=0 drop=4    .0 size=   59893kB time=00:20:04.64 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.371  - error: host.iobroker Caught by controller[34]: frame=24043 fps= 20 q=2.0 size=   59953kB time=00:20:05.72 bitrate= 407.3kbits/s dup=0 drop=4    
frame=24063 fps= 20 q=2.0 size=   60004kB time=00:20:06.80 bitrate= 407.3kbits/s dup=0 drop=4    .0 size=   59978kB time=00:20:06.22 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.372  - error: host.iobroker Caught by controller[36]: frame=24074 fps= 20 q=1.6 size=   60031kB time=00:20:07.23 bitrate= 407.4kbits/s dup=0 drop=4    
2020-01-01 07:20:18.372  - error: host.iobroker Caught by controller[37]: frame=24084 fps= 20 q=2.0 size=   60052kB time=00:20:07.81 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.372  - error: host.iobroker Caught by controller[38]: frame=24095 fps= 20 q=2.0 size=   60081kB time=00:20:08.31 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.372  - error: host.iobroker Caught by controller[39]: frame=24105 fps= 20 q=2.0 size=   60105kB time=00:20:08.82 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.372  - error: host.iobroker Caught by controller[40]: frame=24115 fps= 20 q=2.0 size=   60133kB time=00:20:09.39 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.372  - error: host.iobroker Caught by controller[41]: frame=24125 fps= 20 q=2.0 size=   60158kB time=00:20:09.82 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.372  - error: host.iobroker Caught by controller[42]: frame=24135 fps= 20 q=2.0 size=   60185kB time=00:20:10.33 bitrate= 407.4kbits/s dup=0 drop=4    
2020-01-01 07:20:18.373  - error: host.iobroker Caught by controller[43]: frame=24148 fps= 20 q=2.0 size=   60221kB time=00:20:10.98 bitrate= 407.4kbits/s dup=0 drop=4    
2020-01-01 07:20:18.373  - error: host.iobroker Caught by controller[44]: frame=24158 fps= 20 q=1.6 size=   60247kB time=00:20:11.48 bitrate= 407.4kbits/s dup=0 drop=4    
2020-01-01 07:20:18.373  - error: host.iobroker Caught by controller[45]: frame=24169 fps= 20 q=2.0 size=   60263kB time=00:20:11.98 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.373  - error: host.iobroker Caught by controller[46]: frame=24176 fps= 20 q=2.0 size=   60286kB time=00:20:12.34 bitrate= 407.4kbits/s dup=0 drop=4    
2020-01-01 07:20:18.373  - error: host.iobroker Caught by controller[47]: frame=24189 fps= 20 q=2.0 size=   60318kB time=00:20:13.06 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.373  - error: host.iobroker Caught by controller[48]: frame=24195 fps= 20 q=2.0 size=   60338kB time=00:20:13.35 bitrate= 407.4kbits/s dup=0 drop=4    
2020-01-01 07:20:18.373  - error: host.iobroker Caught by controller[49]: frame=24212 fps= 20 q=2.0 size=   60375kB time=00:20:14.22 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.373  - error: host.iobroker Caught by controller[50]: frame=24222 fps= 20 q=2.0 size=   60402kB time=00:20:14.72 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.373  - error: host.iobroker Caught by controller[51]: frame=24233 fps= 20 q=2.0 size=   60433kB time=00:20:15.22 bitrate= 407.4kbits/s dup=0 drop=4    
2020-01-01 07:20:18.374  - error: host.iobroker Caught by controller[52]: ReferenceError: i is not defined
2020-01-01 07:20:18.374  - error: host.iobroker Caught by controller[52]:     at WebSocketServer.wsServer.broadcast (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:103:54)
2020-01-01 07:20:18.374  - error: host.iobroker Caught by controller[52]:     at VideoStream.on (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:109:26)
2020-01-01 07:20:18.374  - error: host.iobroker Caught by controller[52]:     at VideoStream.emit (events.js:198:13)
2020-01-01 07:20:18.374  - error: host.iobroker Caught by controller[52]:     at Mpeg1Muxer.mpeg1Muxer.on (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:47:17)
2020-01-01 07:20:18.375  - error: host.iobroker Caught by controller[52]:     at Mpeg1Muxer.emit (events.js:198:13)
2020-01-01 07:20:18.375  - error: host.iobroker Caught by controller[52]:     at Socket.Mpeg1Muxer.stream.stdout.on (/opt/iobroker/node_modules/node-rtsp-stream/mpeg1muxer.js:39:17)
2020-01-01 07:20:18.375  - error: host.iobroker Caught by controller[52]:     at Socket.emit (events.js:198:13)
2020-01-01 07:20:18.375  - error: host.iobroker Caught by controller[52]:     at addChunk (_stream_readable.js:287:12)
2020-01-01 07:20:18.375  - error: host.iobroker Caught by controller[52]:     at readableAddChunk (_stream_readable.js:268:11)
2020-01-01 07:20:18.375  - error: host.iobroker Caught by controller[52]:     at Socket.Readable.push (_stream_readable.js:223:10)
2020-01-01 07:20:18.375  - error: host.iobroker Caught by controller[53]: frame=24243 fps= 20 q=2.0 size=   60458kB time=00:20:15.73 bitrate= 407.4kbits/s dup=0 drop=4    
2020-01-01 07:20:18.375  - error: host.iobroker Caught by controller[54]: frame=24253 fps= 20 q=2.0 size=   60471kB time=00:20:16.23 bitrate= 407.3kbits/s dup=0 drop=4    
2020-01-01 07:20:18.376  - info: host.iobroker instance system.adapter.rtspStream.0 terminated with code 0 (NO_ERROR)
2020-01-01 07:20:18.376  - info: host.iobroker Restart adapter system.adapter.rtspStream.0 because enabled
2020-01-01 07:20:37.185  - info: host.iobroker stopInstance system.adapter.history.0 (force=false, process=true)
2020-01-01 07:20:39.190  - info: host.iobroker stopInstance timeout 2000 system.adapter.history.0 killing pid  2206
2020-01-01 07:20:41.705  - info: host.iobroker instance system.adapter.history.0 started with pid 23206
2020-01-01 07:20:43.032  - error: history.0 (23206) history.0 already running
2020-01-01 07:20:43.034  - warn: history.0 (23206) Terminated (ADAPTER_ALREADY_RUNNING): Without reason
2020-01-01 07:20:43.093  - warn: history.0 (2206) Got terminate signal. Checking desired PID: 0 vs own PID 2206
2020-01-01 07:20:43.096  - warn: history.0 (2206) Got terminate signal. Checking desired PID: 23206 vs own PID 2206
2020-01-01 07:20:43.554  - error: host.iobroker instance system.adapter.history.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
2020-01-01 07:20:43.554  - info: host.iobroker Restart adapter system.adapter.history.0 because enabled
2020-01-01 07:20:43.633  - error: host.iobroker instance system.adapter.history.0 terminated with code 156 (156)
2020-01-01 07:20:43.634  - info: host.iobroker Restart adapter system.adapter.history.0 because enabled
2020-01-01 07:20:45.230  - info: host.iobroker stopInstance system.adapter.mihome.0 (force=false, process=true)
2020-01-01 07:20:45.231  - info: host.iobroker stopInstance system.adapter.mihome.0 send kill signal
2020-01-01 07:20:45.756  - info: host.iobroker instance system.adapter.mihome.0 terminated with code 156 (156)
2020-01-01 07:20:47.748  - info: host.iobroker instance system.adapter.mihome.0 started with pid 23218
2020-01-01 07:20:48.483  - info: host.iobroker instance system.adapter.rtspStream.0 started with pid 23229
2020-01-01 07:20:49.054  - debug: rtspStream.0 (23229) Redis Objects: Use Redis connection: 0.0.0.0:9001
2020-01-01 07:20:49.082  - debug: rtspStream.0 (23229) Objects client ready ... initialize now
2020-01-01 07:20:49.085  - debug: rtspStream.0 (23229) Objects create System PubSub Client
2020-01-01 07:20:49.085  - debug: rtspStream.0 (23229) Objects create User PubSub Client
2020-01-01 07:20:49.085  - debug: rtspStream.0 (23229) Objects client initialize lua scripts
2020-01-01 07:20:49.099  - debug: rtspStream.0 (23229) Objects connected to redis: 0.0.0.0:9001
2020-01-01 07:20:49.102  - debug: rtspStream.0 (23229) objectDB connected
2020-01-01 07:20:49.103  - debug: rtspStream.0 (23229) Redis States: Use Redis connection: 0.0.0.0:9000
2020-01-01 07:20:49.110  - debug: rtspStream.0 (23229) States create User PubSub Client
2020-01-01 07:20:49.112  - debug: rtspStream.0 (23229) States create System PubSub Client
2020-01-01 07:20:49.149  - debug: rtspStream.0 (23229) States connected to redis: 0.0.0.0:9000
2020-01-01 07:20:49.149  - debug: rtspStream.0 (23229) statesDB connected
2020-01-01 07:20:50.085  - info: rtspStream.0 (23229) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.rtspStream, node: v10.17.0
2020-01-01 07:20:50.114  - debug: rtspStream.0 (23229) Starting rtsp Stream
2020-01-01 07:20:50.206  - debug: rtspStream.0 (23229) State Change: rtspStream.0.startStream to true ack false
2020-01-01 07:20:50.207  - debug: rtspStream.0 (23229) Start stream on rtsp://admin:admin@192.168.0.88/12with port undefined
2020-01-01 07:21:13.648  - info: host.iobroker instance system.adapter.history.0 started with pid 23273
2020-01-01 07:22:42.488  - error: fullybrowser.0 (14260) Error SendCommand : Error: connect EHOSTUNREACH 192.168.178.22:2323
2020-01-01 07:22:52.266  - debug: rtspStream.0 (23229) system.adapter.admin.0: logging true
`

**Comment by dbweb-ch** [comment]
Hi,
When does this happen? Just randomly while streaming? 
It seems that this comes from the ffmpeg-library, so usually nothing I can fix unfortunately.

**Comment by Ilovegym66** [comment]
Hi, yes, randomly while streaming.. :-( looks like a fault of the ffmpeg-lib. I've tested on different Hosts, the same effect.
