### ISSUE TITLE
Implemented for HiKam S6 succesfully

### ISSUE THREAD

**Issue by manni-2x** [dbweb-ch/ioBroker.rtspstream#3]
Hi,
thanks for very good Work.
I have implemented this in iobroker or HiKam S6 succesfully.  Important is to use the correct SD stream 1 (stream 0 is HD):
rtsp://192.168.178.xx:554/user=admin_password=xxxxxx_channel=1_stream=1.sdp?real_stream
I'v got some Problems by refresh of VIS: break of the stream (Error log see below:).       
Could You implement an additionally  commandline for ffmpeg in iobroker instance configuration to give a possibility to test some options of it?  
I' a programmer, by JS and GIT are not what I use, so is for me not easy to clone(?) your project and make changes.      

MfG
Marian

```2020-01-15 11:46:26.853  - error: rtspStream.0 (2007) uncaught exception: i is not defined
--
2020-01-15 11:46:26.855  - error: rtspStream.0 (2007) ReferenceError: i is not defined
at WebSocketServer.wsServer.broadcast (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:103:54)
at VideoStream.on (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:109:26)
at VideoStream.emit (events.js:198:13)
at Mpeg1Muxer.mpeg1Muxer.on (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:47:17)
at Mpeg1Muxer.emit (events.js:198:13)
at Socket.Mpeg1Muxer.stream.stdout.on (/opt/iobroker/node_modules/node-rtsp-stream/mpeg1muxer.js:39:17)
at Socket.emit (events.js:198:13)
at addChunk (_stream_readable.js:287:12)
at readableAddChunk (_stream_readable.js:268:11)
at Socket.Readable.push (_stream_readable.js:223:10)
2020-01-15 11:46:27.369  - info: rtspStream.0 (2007) terminating
2020-01-15 11:46:27.371  - info: rtspStream.0 (2007) Terminated (NO_ERROR): Without reason
2020-01-15 11:46:27.905  - error: host.MT-PIONAS Caught by controller[3]: frame=11815 fps= 15 q=14.5 size=   39648kB time=00:13:12.04 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.907  - error: host.MT-PIONAS Caught by controller[4]: frame=11822 fps= 15 q=9.9 size=   39677kB time=00:13:12.62 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.907  - error: host.MT-PIONAS Caught by controller[5]: frame=11830 fps= 15 q=13.7 size=   39693kB time=00:13:13.12 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.907  - error: host.MT-PIONAS Caught by controller[6]: frame=11837 fps= 15 q=15.7 size=   39723kB time=00:13:13.63 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.908  - error: host.MT-PIONAS Caught by controller[7]: frame=11845 fps= 15 q=12.2 size=   39740kB time=00:13:14.13 bitrate= 409.9kbits/s speed=   1x
2020-01-15 11:46:27.908  - error: host.MT-PIONAS Caught by controller[8]: frame=11854 fps= 15 q=12.9 size=   39773kB time=00:13:14.64 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.908  - error: host.MT-PIONAS Caught by controller[9]: frame=11861 fps= 15 q=17.6 size=   39802kB time=00:13:15.21 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.909  - error: host.MT-PIONAS Caught by controller[10]: frame=11869 fps= 15 q=13.0 size=   39817kB time=00:13:15.72 bitrate= 409.9kbits/s speed=   1x
2020-01-15 11:46:27.909  - error: host.MT-PIONAS Caught by controller[11]: frame=11876 fps= 15 q=12.5 size=   39847kB time=00:13:16.22 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.909  - error: host.MT-PIONAS Caught by controller[12]: frame=11884 fps= 15 q=13.2 size=   39883kB time=00:13:16.72 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.909  - error: host.MT-PIONAS Caught by controller[13]: frame=11891 fps= 15 q=13.6 size=   39894kB time=00:13:17.23 bitrate= 409.9kbits/s speed=   1x
2020-01-15 11:46:27.910  - error: host.MT-PIONAS Caught by controller[14]: frame=11899 fps= 15 q=12.2 size=   39933kB time=00:13:17.73 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.910  - error: host.MT-PIONAS Caught by controller[15]: frame=11907 fps= 15 q=11.2 size=   39971kB time=00:13:18.24 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.910  - error: host.MT-PIONAS Caught by controller[16]: frame=11915 fps= 15 q=11.7 size=   39982kB time=00:13:18.74 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.910  - error: host.MT-PIONAS Caught by controller[17]: frame=11922 fps= 15 q=14.0 size=   40018kB time=00:13:19.24 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.911  - error: host.MT-PIONAS Caught by controller[18]: frame=11930 fps= 15 q=8.1 size=   40052kB time=00:13:19.75 bitrate= 410.3kbits/s speed=   1x
2020-01-15 11:46:27.911  - error: host.MT-PIONAS Caught by controller[19]: frame=11939 fps= 15 q=12.0 size=   40070kB time=00:13:20.32 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.911  - error: host.MT-PIONAS Caught by controller[20]: frame=11946 fps= 15 q=15.3 size=   40101kB time=00:13:20.90 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.911  - error: host.MT-PIONAS Caught by controller[21]: frame=11954 fps= 15 q=10.3 size=   40134kB time=00:13:21.33 bitrate= 410.3kbits/s speed=   1x
2020-01-15 11:46:27.912  - error: host.MT-PIONAS Caught by controller[22]: frame=11962 fps= 15 q=11.8 size=   40150kB time=00:13:21.84 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.912  - error: host.MT-PIONAS Caught by controller[23]: frame=11969 fps= 15 q=16.9 size=   40179kB time=00:13:22.41 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.912  - error: host.MT-PIONAS Caught by controller[24]: frame=11977 fps= 15 q=13.2 size=   40193kB time=00:13:22.92 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.912  - error: host.MT-PIONAS Caught by controller[25]: frame=11984 fps= 15 q=13.0 size=   40223kB time=00:13:23.42 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.913  - error: host.MT-PIONAS Caught by controller[26]: frame=11993 fps= 15 q=20.0 size=   40253kB time=00:13:23.93 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.913  - error: host.MT-PIONAS Caught by controller[27]: frame=12000 fps= 15 q=16.2 size=   40265kB time=00:13:24.50 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.913  - error: host.MT-PIONAS Caught by controller[28]: frame=12008 fps= 15 q=14.1 size=   40299kB time=00:13:25.00 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.914  - error: host.MT-PIONAS Caught by controller[29]: frame=12015 fps= 15 q=13.5 size=   40329kB time=00:13:25.51 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.914  - error: host.MT-PIONAS Caught by controller[30]: frame=12023 fps= 15 q=14.8 size=   40343kB time=00:13:26.01 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.914  - error: host.MT-PIONAS Caught by controller[31]: frame=12031 fps= 15 q=12.4 size=   40378kB time=00:13:26.52 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.914  - error: host.MT-PIONAS Caught by controller[32]: frame=12038 fps= 15 q=8.5 size=   40410kB time=00:13:27.09 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.915  - error: host.MT-PIONAS Caught by controller[33]: frame=12047 fps= 15 q=11.7 size=   40425kB time=00:13:27.60 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.915  - error: host.MT-PIONAS Caught by controller[34]: frame=12054 fps= 15 q=16.4 size=   40454kB time=00:13:28.10 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.915  - error: host.MT-PIONAS Caught by controller[35]: frame=12062 fps= 15 q=12.7 size=   40485kB time=00:13:28.60 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.915  - error: host.MT-PIONAS Caught by controller[36]: frame=12070 fps= 15 q=15.8 size=   40501kB time=00:13:29.11 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.916  - error: host.MT-PIONAS Caught by controller[37]: frame=12077 fps= 15 q=18.0 size=   40530kB time=00:13:29.68 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.916  - error: host.MT-PIONAS Caught by controller[38]: frame=12086 fps= 15 q=10.2 size=   40564kB time=00:13:30.26 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.916  - error: host.MT-PIONAS Caught by controller[39]: frame=12094 fps= 15 q=14.1 size=   40578kB time=00:13:30.76 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.916  - error: host.MT-PIONAS Caught by controller[40]: frame=12101 fps= 15 q=16.0 size=   40608kB time=00:13:31.20 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.917  - error: host.MT-PIONAS Caught by controller[41]: frame=12109 fps= 15 q=11.3 size=   40625kB time=00:13:31.77 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.917  - error: host.MT-PIONAS Caught by controller[42]: frame=12116 fps= 15 q=12.0 size=   40658kB time=00:13:32.28 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.917  - error: host.MT-PIONAS Caught by controller[43]: frame=12124 fps= 15 q=12.8 size=   40693kB time=00:13:32.85 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.917  - error: host.MT-PIONAS Caught by controller[44]: frame=12131 fps= 15 q=9.8 size=   40705kB time=00:13:33.36 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.918  - error: host.MT-PIONAS Caught by controller[45]: frame=12140 fps= 15 q=14.6 size=   40737kB time=00:13:33.86 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.918  - error: host.MT-PIONAS Caught by controller[46]: frame=12147 fps= 15 q=12.6 size=   40772kB time=00:13:34.36 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.918  - error: host.MT-PIONAS Caught by controller[47]: frame=12155 fps= 15 q=11.5 size=   40783kB time=00:13:34.87 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.918  - error: host.MT-PIONAS Caught by controller[48]: frame=12163 fps= 15 q=13.6 size=   40818kB time=00:13:35.37 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.919  - error: host.MT-PIONAS Caught by controller[49]: frame=12170 fps= 15 q=9.7 size=   40848kB time=00:13:35.88 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.919  - error: host.MT-PIONAS Caught by controller[50]: frame=12178 fps= 15 q=12.8 size=   40863kB time=00:13:36.45 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.919  - error: host.MT-PIONAS Caught by controller[51]: frame=12186 fps= 15 q=15.4 size=   40898kB time=00:13:36.96 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.920  - error: host.MT-PIONAS Caught by controller[52]: frame=12194 fps= 15 q=10.7 size=   40928kB time=00:13:37.39 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.920  - error: host.MT-PIONAS Caught by controller[53]: frame=12201 fps= 15 q=13.0 size=   40943kB time=00:13:37.96 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.920  - error: host.MT-PIONAS Caught by controller[54]: frame=12209 fps= 15 q=15.3 size=   40975kB time=00:13:38.47 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.921  - error: host.MT-PIONAS Caught by controller[55]: frame=12217 fps= 15 q=12.3 size=   40990kB time=00:13:38.97 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.921  - error: host.MT-PIONAS Caught by controller[56]: frame=12224 fps= 15 q=14.0 size=   41019kB time=00:13:39.48 bitrate= 410.0kbits/s speed=   1x
2020-01-15 11:46:27.922  - error: host.MT-PIONAS Caught by controller[57]: frame=12232 fps= 15 q=13.8 size=   41053kB time=00:13:39.98 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.922  - error: host.MT-PIONAS Caught by controller[58]: frame=12239 fps= 15 q=14.5 size=   41065kB time=00:13:40.34 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.922  - error: host.MT-PIONAS Caught by controller[59]: ReferenceError: i is not defined
2020-01-15 11:46:27.923  - error: host.MT-PIONAS Caught by controller[59]:     at WebSocketServer.wsServer.broadcast (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:103:54)
2020-01-15 11:46:27.923  - error: host.MT-PIONAS Caught by controller[59]:     at VideoStream.on (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:109:26)
2020-01-15 11:46:27.923  - error: host.MT-PIONAS Caught by controller[59]:     at VideoStream.emit (events.js:198:13)
2020-01-15 11:46:27.923  - error: host.MT-PIONAS Caught by controller[59]:     at Mpeg1Muxer.mpeg1Muxer.on (/opt/iobroker/node_modules/node-rtsp-stream/videoStream.js:47:17)
2020-01-15 11:46:27.924  - error: host.MT-PIONAS Caught by controller[59]:     at Mpeg1Muxer.emit (events.js:198:13)
2020-01-15 11:46:27.924  - error: host.MT-PIONAS Caught by controller[59]:     at Socket.Mpeg1Muxer.stream.stdout.on (/opt/iobroker/node_modules/node-rtsp-stream/mpeg1muxer.js:39:17)
2020-01-15 11:46:27.924  - error: host.MT-PIONAS Caught by controller[59]:     at Socket.emit (events.js:198:13)
2020-01-15 11:46:27.925  - error: host.MT-PIONAS Caught by controller[59]:     at addChunk (_stream_readable.js:287:12)
2020-01-15 11:46:27.925  - error: host.MT-PIONAS Caught by controller[59]:     at readableAddChunk (_stream_readable.js:268:11)
2020-01-15 11:46:27.925  - error: host.MT-PIONAS Caught by controller[59]:     at Socket.Readable.push (_stream_readable.js:223:10)
2020-01-15 11:46:27.925  - error: host.MT-PIONAS Caught by controller[60]: frame=12247 fps= 15 q=12.0 size=   41100kB time=00:13:41.06 bitrate= 410.1kbits/s speed=   1x
2020-01-15 11:46:27.926  - error: host.MT-PIONAS Caught by controller[61]: frame=12254 fps= 15 q=7.5 size=   41135kB time=00:13:41.56 bitrate= 410.2kbits/s speed=   1x
2020-01-15 11:46:27.926  - info: host.MT-PIONAS instance system.adapter.rtspStream.0 terminated with code 0 (NO_ERROR)
2020-01-15 11:46:27.927  - info: host.MT-PIONAS Restart adapter system.adapter.rtspStream.0 because enabled
2020-01-15 11:46:54.629  - info: web.0 (799) <==Disconnect system.user.admin from ::ffff:192.168.178.47 vis.0
2020-01-15 11:46:57.951  - info: host.MT-PIONAS instance system.adapter.rtspStream.0 started with pid 2077
2020-01-15 11:46:59.536  - info: web.0 (799) ==>Connected system.user.admin from ::ffff:192.168.178.47
2020-01-15 11:47:00.741  - info: rtspStream.0 (2077) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.rtspStream, node: v10.17.0
2020-01-15 11:47:28.764  - info: web.0 (799) <==Disconnect system.user.admin from ::ffff:192.168.178.47 vis.0
2020-01-15 11:47:29.427  - info: web.0 (799) ==>Connected system.user.admin from ::ffff:192.168.178.47
2020-01-15 11:52:19.185  - info: host.MT-PIONAS stopInstance system.adapter.rtspStream.0 (force=false, process=true)
2020-01-15 11:52:19.187  - info: host.MT-PIONAS stopInstance system.adapter.rtspStream.0 send kill signal
2020-01-15 11:52:19.193  - info: rtspStream.0 (2077) Got terminate signal TERMINATE_YOURSELF
2020-01-15 11:52:19.696  - info: rtspStream.0 (2077) terminating
2020-01-15 11:52:19.698  - info: rtspStream.0 (2077) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
2020-01-15 11:52:20.189  - info: host.MT-PIONAS stopInstance system.adapter.rtspStream.0 killing pid 2077
2020-01-15 11:52:20.226  - error: host.MT-PIONAS Caught by controller[2]: frame= 4292 fps= 15 q=12.1 size=   14599kB time=00:04:47.91 bitrate= 415.4kbits/s speed=1.01x
2020-01-15 11:52:20.228  - error: host.MT-PIONAS Caught by controller[3]: frame= 4301 fps= 15 q=15.7 size=   14636kB time=00:04:48.42 bitrate= 415.7kbits/s speed=1.01x
2020-01-15 11:52:20.231  - error: host.MT-PIONAS Caught by controller[4]: frame= 4308 fps= 15 q=10.9 size=   14650kB time=00:04:48.99 bitrate= 415.3kbits/s speed=1.01x
2020-01-15 11:52:20.231  - error: host.MT-PIONAS Caught by controller[5]: frame= 4316 fps= 15 q=11.5 size=   14682kB time=00:04:49.50 bitrate= 415.5kbits/s speed=1.01x
2020-01-15 11:52:20.231  - error: host.MT-PIONAS Caught by controller[6]: frame= 4324 fps= 15 q=12.5 size=   14718kB time=00:04:50.00 bitrate= 415.8kbits/s speed=1.01x
2020-01-15 11:52:20.232  - error: host.MT-PIONAS Caught by controller[7]: frame= 4331 fps= 15 q=13.0 size=   14730kB time=00:04:50.58 bitrate= 415.3kbits/s speed=1.01x
2020-01-15 11:52:20.232  - error: host.MT-PIONAS Caught by controller[8]: frame= 4339 fps= 15 q=13.2 size=   14764kB time=00:04:51.01 bitrate= 415.6kbits/s speed=1.01x
2020-01-15 11:52:20.232  - error: host.MT-PIONAS Caught by controller[9]: frame= 4346 fps= 15 q=11.2 size=   14793kB time=00:04:51.58 bitrate= 415.6kbits/s speed=1.01x
2020-01-15 11:52:20.233  - error: host.MT-PIONAS Caught by controller[10]: frame= 4355 fps= 15 q=13.6 size=   14808kB time=00:04:52.09 bitrate= 415.3kbits/s speed=1.01x
2020-01-15 11:52:20.233  - error: host.MT-PIONAS Caught by controller[11]: frame= 4363 fps= 15 q=14.3 size=   14840kB time=00:04:52.59 bitrate= 415.5kbits/s speed=1.01x
2020-01-15 11:52:20.233  - error: host.MT-PIONAS Caught by controller[12]: frame= 4370 fps= 15 q=10.1 size=   14870kB time=00:04:53.17 bitrate= 415.5kbits/s speed=1.01x
2020-01-15 11:52:20.233  - error: host.MT-PIONAS Caught by controller[13]: frame= 4378 fps= 15 q=14.2 size=   14885kB time=00:04:53.60 bitrate= 415.3kbits/s speed=1.01x
2020-01-15 11:52:20.234  - error: host.MT-PIONAS Caught by controller[14]: frame= 4385 fps= 15 q=15.8 size=   14917kB time=00:04:54.10 bitrate= 415.5kbits/s speed=1.01x
2020-01-15 11:52:20.234  - error: host.MT-PIONAS Caught by controller[15]: frame= 4394 fps= 15 q=7.5 size=   14956kB time=00:04:54.68 bitrate= 415.8kbits/s speed=1.01x
2020-01-15 11:52:20.234  - error: host.MT-PIONAS Caught by controller[16]: frame= 4402 fps= 15 q=10.6 size=   14971kB time=00:04:55.18 bitrate= 415.5kbits/s speed=1.01x
2020-01-15 11:52:20.234  - error: host.MT-PIONAS Caught by controller[17]: frame= 4409 fps= 15 q=18.4 size=   15000kB time=00:04:55.69 bitrate= 415.6kbits/s speed=1.01x
2020-01-15 11:52:20.235  - error: host.MT-PIONAS Caught by controller[18]: frame= 4416 fps= 15 q=13.3 size=   15013kB time=00:04:56.19 bitrate= 415.2kbits/s speed=1.01x
2020-01-15 11:52:20.235  - error: host.MT-PIONAS Caught by controller[19]: frame= 4424 fps= 15 q=15.5 size=   15044kB time=00:04:56.77 bitrate= 415.3kbits/s speed=1.01x
2020-01-15 11:52:20.235  - error: host.MT-PIONAS Caught by controller[20]: frame= 4432 fps= 15 q=15.9 size=   15075kB time=00:04:57.27 bitrate= 415.4kbits/s speed=1.01x
2020-01-15 11:52:20.235  - error: host.MT-PIONAS Caught by controller[21]: frame= 4440 fps= 15 q=13.8 size=   15090kB time=00:04:57.78 bitrate= 415.1kbits/s speed=1.01x
2020-01-15 11:52:20.236  - error: host.MT-PIONAS Caught by controller[22]: frame= 4447 fps= 15 q=12.7 size=   15121kB time=00:04:58.28 bitrate= 415.3kbits/s speed=1.01x
2020-01-15 11:52:20.236  - error: host.MT-PIONAS Caught by controller[23]: frame= 4455 fps= 15 q=10.1 size=   15160kB time=00:04:58.78 bitrate= 415.6kbits/s speed=1.01x
2020-01-15 11:52:20.236  - error: host.MT-PIONAS Caught by controller[24]: frame= 4463 fps= 15 q=9.9 size=   15174kB time=00:04:59.36 bitrate= 415.2kbits/s speed=1.01x
2020-01-15 11:52:20.236  - error: host.MT-PIONAS Caught by controller[25]: frame= 4470 fps= 15 q=15.0 size=   15207kB time=00:04:59.79 bitrate= 415.5kbits/s speed=1.01x
2020-01-15 11:52:20.237  - error: host.MT-PIONAS Caught by controller[26]: frame= 4478 fps= 15 q=9.8 size=   15239kB time=00:05:00.30 bitrate= 415.7kbits/s speed=1.01x
2020-01-15 11:52:20.237  - error: host.MT-PIONAS Caught by controller[27]: frame= 4485 fps= 15 q=12.0 size=   15252kB time=00:05:00.87 bitrate= 415.3kbits/s speed=1.01x
2020-01-15 11:52:20.237  - error: host.MT-PIONAS Caught by controller[28]: frame= 4493 fps= 15 q=15.3 size=   15286kB time=00:05:01.38 bitrate= 415.5kbits/s speed=1.01x
2020-01-15 11:52:20.238  - error: host.MT-PIONAS Caught by controller[29]: frame= 4501 fps= 15 q=15.0 size=   15301kB time=00:05:01.88 bitrate= 415.2kbits/s speed=1.01x
2020-01-15 11:52:20.238  - error: host.MT-PIONAS Caught by controller[30]: frame= 4508 fps= 15 q=15.8 size=   15327kB time=00:05:02.38 bitrate= 415.2kbits/s speed=1.01x
2020-01-15 11:52:20.238  - error: host.MT-PIONAS Caught by controller[31]: frame= 4516 fps= 15 q=14.8 size=   15361kB time=00:05:02.89 bitrate= 415.5kbits/s speed=1.01x
2020-01-15 11:52:20.238  - error: host.MT-PIONAS Caught by controller[32]: frame= 4523 fps= 15 q=14.8 size=   15373kB time=00:05:03.39 bitrate= 415.1kbits/s speed=1.01x
2020-01-15 11:52:20.239  - error: host.MT-PIONAS Caught by controller[33]: frame= 4532 fps= 15 q=13.7 size=   15405kB time=00:05:03.90 bitrate= 415.3kbits/s speed=1.01x
2020-01-15 11:52:20.239  - error: host.MT-PIONAS Caught by controller[34]: frame= 4540 fps= 15 q=15.1 size=   15440kB time=00:05:04.40 bitrate= 415.5kbits/s speed=1.01x
2020-01-15 11:52:20.239  - error: host.MT-PIONAS Caught by controller[35]: frame= 4547 fps= 15 q=13.0 size=   15451kB time=00:05:05.05 bitrate= 414.9kbits/s speed=1.01x
2020-01-15 11:52:20.239  - error: host.MT-PIONAS Caught by controller[36]: frame= 4555 fps= 15 q=13.6 size=   15486kB time=00:05:05.55 bitrate= 415.2kbits/s speed=1.01x
2020-01-15 11:52:20.240  - error: host.MT-PIONAS Caught by controller[37]: frame= 4562 fps= 15 q=12.8 size=   15513kB time=00:05:06.06 bitrate= 415.2kbits/s speed=1.01x
2020-01-15 11:52:20.240  - error: host.MT-PIONAS Caught by controller[38]: frame= 4570 fps= 15 q=14.0 size=   15529kB time=00:05:06.49 bitrate= 415.1kbits/s speed=1.01x
2020-01-15 11:52:20.240  - error: host.MT-PIONAS Caught by controller[39]: frame= 4577 fps= 15 q=16.9 size=   15561kB time=00:05:07.06 bitrate= 415.1kbits/s speed=1.01x
2020-01-15 11:52:20.240  - error: host.MT-PIONAS Caught by controller[40]: frame= 4585 fps= 15 q=12.3 size=   15576kB time=00:05:07.50 bitrate= 414.9kbits/s speed=1.01x
2020-01-15 11:52:20.241  - error: host.MT-PIONAS Caught by controller[41]: frame= 4593 fps= 15 q=13.3 size=   15605kB time=00:05:08.07 bitrate= 415.0kbits/s speed=1.01x
2020-01-15 11:52:20.241  - error: host.MT-PIONAS Caught by controller[42]: frame= 4601 fps= 15 q=17.9 size=   15638kB time=00:05:08.58 bitrate= 415.1kbits/s speed=1.01x
2020-01-15 11:52:20.241  - error: host.MT-PIONAS Caught by controller[43]: frame= 4608 fps= 15 q=16.0 size=   15650kB time=00:05:09.08 bitrate= 414.8kbits/s speed=1.01x
2020-01-15 11:52:20.242  - error: host.MT-PIONAS Caught by controller[44]: frame= 4616 fps= 15 q=12.0 size=   15683kB time=00:05:09.58 bitrate= 415.0kbits/s speed=1.01x
2020-01-15 11:52:20.242  - error: host.MT-PIONAS Caught by controller[45]: frame= 4624 fps= 15 q=14.1 size=   15716kB time=00:05:10.09 bitrate= 415.2kbits/s speed=1.01x
2020-01-15 11:52:20.245  - error: host.MT-PIONAS Caught by controller[46]: frame= 4631 fps= 15 q=14.3 size=   15728kB time=00:05:10.66 bitrate= 414.7kbits/s speed=1.01x
2020-01-15 11:52:20.246  - error: host.MT-PIONAS Caught by controller[47]: frame= 4639 fps= 15 q=13.9 size=   15765kB time=00:05:11.17 bitrate= 415.0kbits/s speed=1.01x
2020-01-15 11:52:20.246  - error: host.MT-PIONAS Caught by controller[48]: frame= 4646 fps= 15 q=8.7 size=   15795kB time=00:05:11.67 bitrate= 415.2kbits/s speed=1.01x
2020-01-15 11:52:20.246  - error: host.MT-PIONAS Caught by controller[49]: frame= 4654 fps= 15 q=12.3 size=   15811kB time=00:05:12.10 bitrate= 415.0kbits/s speed=1.01x
2020-01-15 11:52:20.247  - error: host.MT-PIONAS Caught by controller[50]: frame= 4661 fps= 15 q=16.9 size=   15840kB time=00:05:12.68 bitrate= 415.0kbits/s speed=1.01x
2020-01-15 11:52:20.247  - error: host.MT-PIONAS Caught by controller[51]: frame= 4670 fps= 15 q=13.2 size=   15870kB time=00:05:13.18 bitrate= 415.1kbits/s speed=1.01x
2020-01-15 11:52:20.247  - error: host.MT-PIONAS Caught by controller[52]: frame= 4676 fps= 15 q=14.2 size=   15883kB time=00:05:13.69 bitrate= 414.8kbits/s speed=1.01x
2020-01-15 11:52:20.247  - error: host.MT-PIONAS Caught by controller[53]: frame= 4685 fps= 15 q=18.1 size=   15916kB time=00:05:14.19 bitrate= 415.0kbits/s speed=1.01x
2020-01-15 11:52:20.248  - error: host.MT-PIONAS Caught by controller[54]: frame= 4693 fps= 15 q=11.7 size=   15932kB time=00:05:14.70 bitrate= 414.7kbits/s speed=1.01x
2020-01-15 11:52:20.248  - error: host.MT-PIONAS Caught by controller[55]: frame= 4700 fps= 15 q=13.3 size=   15965kB time=00:05:15.27 bitrate= 414.8kbits/s speed=1.01x
2020-01-15 11:52:20.248  - error: host.MT-PIONAS Caught by controller[56]: frame= 4708 fps= 15 q=14.2 size=   15998kB time=00:05:15.78 bitrate= 415.0kbits/s speed=1.01x
2020-01-15 11:52:20.249  - error: host.MT-PIONAS Caught by controller[57]: frame= 4715 fps= 15 q=14.3 size=   16010kB time=00:05:16.28 bitrate= 414.7kbits/s speed=1.01x
2020-01-15 11:52:20.249  - error: host.MT-PIONAS Caught by controller[58]: frame= 4723 fps= 15 q=11.7 size=   16045kB time=00:05:16.78 bitrate= 414.9kbits/s speed=1.01x
2020-01-15 11:52:20.249  - error: host.MT-PIONAS Caught by controller[59]: frame= 4731 fps= 15 q=14.3 size=   16074kB time=00:05:17.29 bitrate= 415.0kbits/s speed=1.01x
2020-01-15 11:52:20.250  - info: host.MT-PIONAS instance system.adapter.rtspStream.0 terminated with code 156 (156) ```

**Comment by dbweb-ch** [comment]
Hi Marian,

I made some changes, including your "free" ffmpeg-Options. You can enter json valid code there and it will be added, or replace the default options.
Breaking streams is something you can only play around with the options as the reason is a combination of hardware, camera, ffmpeg etc.
