### ISSUE TITLE
Start of stream stops immediately with error

### ISSUE THREAD

**Issue by Damian411** [dbweb-ch/ioBroker.rtspstream#9]
Great adapter!
But if I start the stream then the instance throws immediately an error.
Probably the log will help you to locate and fix the cause:

`
2021-01-06 07:06:46.992  - info: host.iobroker "system.adapter.rtspstream.0" enabled
2021-01-06 07:06:47.008  - info: host.iobroker instance system.adapter.rtspstream.0 started with pid 5667
2021-01-06 07:06:47.260  - debug: rtspstream.0 (5667) Redis Objects: Use Redis connection: 127.0.0.1:9001
2021-01-06 07:06:47.280  - debug: rtspstream.0 (5667) Objects client ready ... initialize now
2021-01-06 07:06:47.281  - debug: rtspstream.0 (5667) Objects create System PubSub Client
2021-01-06 07:06:47.282  - debug: rtspstream.0 (5667) Objects create User PubSub Client
2021-01-06 07:06:47.282  - debug: rtspstream.0 (5667) Objects client initialize lua scripts
2021-01-06 07:06:47.291  - debug: rtspstream.0 (5667) Objects connected to redis: 127.0.0.1:9001
2021-01-06 07:06:47.294  - debug: rtspstream.0 (5667) objectDB connected
2021-01-06 07:06:47.294  - debug: rtspstream.0 (5667) Redis States: Use Redis connection: 127.0.0.1:9000
2021-01-06 07:06:47.298  - debug: rtspstream.0 (5667) States create User PubSub Client
2021-01-06 07:06:47.300  - debug: rtspstream.0 (5667) States create System PubSub Client
2021-01-06 07:06:47.305  - debug: rtspstream.0 (5667) States connected to redis: 127.0.0.1:9000
2021-01-06 07:06:47.305  - debug: rtspstream.0 (5667) statesDB connected
2021-01-06 07:06:48.007  - info:  rtspstream.0 (5667) starting. Version 0.0.4 in  /opt/iobroker/node_modules/iobroker.rtspstream, node: v12.20.1,  js-controller: 3.1.6
2021-01-06 07:06:48.018  - debug: rtspstream.0 (5667) Starting rtsp Stream
2021-01-06 07:06:48.062  - info: rtspstream.0 (5667) Number of streams: 1
2021-01-06 07:07:08.134  - warn: rtspstream.0 (5667) State Change: rtspstream.0.Indoor.startStream to true ack false
2021-01-06 07:07:08.135  - debug: rtspstream.0 (5667) Action: startStream Name: IndoorStatetrue
2021-01-06 07:07:08.180  - info: rtspstream.0 (5667) Setting stream Resolution to 1920 x 1080
**2021-01-06 07:07:08.183  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-01-06 07:07:08.183  - error: rtspstream.0 (5667) unhandled promise rejection: Cannot read property 'videoPort' of undefined
2021-01-06 07:07:08.184  - error: rtspstream.0 (5667) TypeError: Cannot read property 'videoPort' of undefined
at rtspstream.onStateChange (/opt/iobroker/node_modules/iobroker.rtspstream/main.js:140:98)
at processTicksAndRejections (internal/process/task_queues.js:97:5)**
2021-01-06 07:07:08.687  - info: rtspstream.0 (5667) terminating
2021-01-06 07:07:08.687  - info: rtspstream.0 (5667) Terminated (NO_ERROR): Without reason
2021-01-06 07:07:09.201  - info: host.iobroker instance system.adapter.rtspstream.0 terminated with code 0 (NO_ERROR)
2021-01-06 07:07:09.203  - info: host.iobroker Restart adapter system.adapter.rtspstream.0 because enabled

`

**Comment by dbweb-ch** [comment]
After the logmessage "Number of streams: 1" there should be a message 
`"'Stream ' + channels[idx].common.name + ' using TcpPort ' + TcpPort.val"`
Followed by
`'Stream ' + channels[idx].common.name + ' starting Server on Port ' + Port.val`

Did you set up the ports and everything correctly? Did it work with the last version or is this the first time you are using this adapter?

**Comment by Damian411** [comment]
Yes, it is the first time with the adapter.
I send you the screenshots of my config und objects.

Config:
![Screenshot_config](https://user-images.githubusercontent.com/32341615/103766658-7b6ecf80-501f-11eb-9b76-11d07f1c619a.jpg)

Objects:
![Screenshot_objects](https://user-images.githubusercontent.com/32341615/103766661-7c9ffc80-501f-11eb-8de3-29863d506981.jpg)

Now the stream works after some hours, but with another error in log:
![Screenshot_error](https://user-images.githubusercontent.com/32341615/103767134-60e92600-5020-11eb-94d4-75bb91139b5e.jpg)

I will continue to monitor this, but we should fix the bugs above.

Thanks

**Comment by Damian411** [comment]
Here more information about the issue:
The error "Cannot read property 'videoPort' of undefined" happens, if the rtspUrl is "rtsp://10.0.10.21/live0" (without Port). 
The start of the stream works with "rtsp://10.0.10.21:554/live0" (with port). I assumed that the port must be entered no more, since it is already in the tcpPort object.
After changing the rtspUrl I need to reboot the hole VM (or wait some hours) to get the error away and the stream works.

Is this a bug, I would assume that the port from tcpPort is used?

**Comment by dbweb-ch** [comment]
The Port you enter is not the port of the camera stream, it is the port of the server the adapter creates. You can use the same port as from the camera if the camera is not on same computer as iobroker, otherwise it has to be a different port.
Don't know if I call this a bug as it is due to misconfiguration.

**Comment by Damian411** [comment]
I wasn't aware of that, I thought it was the port on the camera for the Rtsp stream, as the field is right next to the stream URL. Then it is a misconfiguration. Perhaps you could give the field another more clear name to prevent other user of this mistake.

**Comment by dbweb-ch** [comment]
Didn't find a better name...any idea?

**Comment by Damian411** [comment]
You wrote it is the port for the server which the adapter creates. Perhaps:
serverPort
adapterPort
internalPort

**Comment by dbweb-ch** [comment]
Used adapter port, changed.
